EmbarkStudios/tame-index

.github/workflows/rust-ci.yml, src/index.rs, src/index/git_remote.rs, src/lib.rs
- Add helpers to GitError
- Make gix and reqwest exported via crate::externals
While working on a PR to resolve https://github.com/obi1kenobi/cargo-semver-checks/issues/487, that crate was looking at the error for git operations to determine if they should be retried, which is....unfortunately way more complicated with gix. So this just adds helper methods on GitError to make that use case nicer.
=> Fixups for `cargo-semver-checks`

CHANGELOG.md, src/index/git_remote.rs, src/utils.rs, src/utils/git.rs, tests/git.rs
This PR makes a big change to how the RemoteGitIndex performs fetches (and clones) and subsequently reads blobs, to resolve issues discovered while doing https://github.com/obi1kenobi/cargo-semver-checks/pull/506
Previously when performing a fetch, we also updated references so that HEAD pointed at the same commit as the remote HEAD. This works fine in local operation and in tests, but had a drawback, namely
```
Error: Failed to update references to their new position to match their remote locations
Caused by:
0: The reflog could not be created or updated
1: reflog messages need a committer which isn't set
```
can occur in CI environments. My attempts to fix this...failed (configuring a committer name + email before editing references).
Then I noticed …
=> Write and use `FETCH_HEAD`

CHANGELOG.md, src/index/location.rs, src/utils.rs
Non-official cargo builds may have differing output for `cargo -V` that the previous code wasn't accounting for, the output is now properly trimmed to remove excess whitespace before attempting to parse it into a semver.
Resolves: #8
=> Fix issue with cargo version parsing

CHANGELOG.md, src/index/local.rs, src/krate.rs, tests/cache.rs, tests/local.rs, tests/sparse.rs, tests/utils.rs
Incredibly unfortunate, but for full compatibility with crates.io, and possibly other indices, we need to be able to deserialize crates from the index that have invalid versions according to the the semver spec (as implemented in `semver`).
See https://github.com/rustsec/rustsec/issues/759
=> Use string versions

CHANGELOG.md, src/utils.rs
This matches cargo's behavior, any .git extension is always stripped before ident hashing
=> Fix git url canonicalization

src/index/git_remote.rs
Makes the locking behavior configurable by API users. 
Needed for `cargo audit` to avoid inexplicable hangs when waiting on a lock: it will first attempt to lock the directory immediately, and if that fails, print a message and only after that start waiting for the lock.
#12, https://github.com/rustsec/rustsec/pull/934
=> Make locking behavior configurable

Cargo.toml
Keep `webpki-roots` enabled by default, but allow optionally using `rustls-native-certs` instead.
This is needed for `cargo audit` which sometimes runs in strange enterprise environments where all HTTPS traffic is intercepted by a MitM proxy, and it's impossible to contact the outside world without using the OS's native HTTPS certificate store.
This is the approach to configuration recommended by @Byron, here: https://github.com/Byron/gitoxide/issues/991
I have verified with `cargo tree` that the features are toggled correctly.
- https://github.com/rustsec/rustsec/issues/939
- https://github.com/Byron/gitoxide/issues/991
=> Allow using `rustls-native-certs` instead of `webpki-roots`

CHANGELOG.md, Cargo.toml, deny.toml, src/error.rs, src/index.rs, src/index/combo.rs, src/index/sparse.rs, src/index/sparse_remote.rs, src/lib.rs, tests/sparse.rs
This changes the `SparseIndex` API slightly to allow for zero disk I/O when making requests to the remote HTTP index.
Resolves: #16
=> General fixups

src/utils.rs
This is the fix for https://github.com/EmbarkStudios/cargo-deny/issues/548 as the hash was correct since it takes the entirety of the user provided url into account, but it wasn't stripping off the user portion of the url causing it to look at the wrong local directory.
=> Fix ssh url -> local directory mapping

benches/sparse.rs, src/index/sparse.rs, tests/sparse.rs
Do not force HTTP/2. Corporate transparent proxies often do not support it, but `cargo audit` needs to run in these environments.
After this change HTTP/2 will be used where available, but the download will not fail if it's not.
https://github.com/rustsec/rustsec/issues/988
=> Don't force HTTP/2

Cargo.toml, src/index/git_remote.rs
Please note that I have removed the `max-performance-safe` feature
which pushes the choice to the consumer of (any) library that uses
`gix`. It's also causing less C to be compiled by default.
An upgrade to the latest `gix`, which includes less dependencies now and compiles a little faster
because of it. It also avoids making decisions about performance (and the inclusion of C-crates)
by removing the `max-performance-safe` feature.
The motivation for this update is to get a new `tame-index` release for consumption in [this PR](https://github.com/obi1kenobi/cargo-semver-checks/pull/531)
so that it can also use the latest `gix` version without duplication.
None
=> update `gix` to the latest version

CHANGELOG.md, src/error.rs, src/index/git_remote.rs, src/index/location.rs
=> Reduce error size

src/utils/flock/unix.rs
#33 introduced a compile error when targeting (at least) `-musl` but possibly other unixes.
=> Fix building on musl

src/utils.rs, tests/git.rs
Just as [cargo does](https://github.com/rust-lang/cargo/blob/0871c0e2f4b6d4f95b7408fb8cef8ad3c9c8d834/src/cargo/core/source_id.rs#L930-L936), ignore the 2 tests that depend on the target being little endian.
Resolves: #36
=> Ignore tests that depend on endianess

src/index/git_remote.rs, tests/git.rs
This wasn't caught in tests since they always just used the root of the temp directory, and in most cases users will already have the index directories created for them by cargo, but of course that is changing as sparse has been the default for months now.
Resolves: #38
=> Fix cloning in presence of missing dir

Cargo.toml, deny.toml, tests/git.rs
By default gix will honor the user's settings (repo, global etc) but this breaks testing if the user has GPG signing enabled, which causes the commit ids to be different from what's expected.
Resolves: #29
=> Force disable GPG commit signing in tests

CHANGELOG.md, src/error.rs, src/index.rs, src/index/local.rs
=> Add ComboIndexCache::cache_path

Cargo.lock, Cargo.toml
The relevant advisories are the following:
* https://github.com/Byron/gitoxide/security/advisories/GHSA-49jc-r788-3fc9
* https://github.com/Byron/gitoxide/security/advisories/GHSA-7w47-3wg8-547c
A release would be helpful as `rustsec` needs it to be able to upgrade itself.
Related issue: https://github.com/Byron/gitoxide/issues/1377
=> upgrade `gix` from v0.62 to v0.63 for security patches

.github/pull_request_template.md
These paths seem to be relative to the PR url, not the source source file per [markdown docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#relative-links), so these were going to the organization rather than the repo.
This feels like a github issue, since having the links be relative to the published url isn't very template-like, but in the mean time this makes the links clickable.
List related issues here
=> Fix broken links in the pull request template

.github/workflows/rust-ci.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, deny.toml, src/error.rs, src/index.rs, src/lib.rs, src/utils.rs, tests/git.rs
- **Add gix-curl feature**
- **Update crates**
```
Updating addr2line v0.21.0 -> v0.22.0 (latest: v0.24.0)
Updating allocator-api2 v0.2.16 -> v0.2.18
Updating arc-swap v1.7.0 -> v1.7.1
Updating async-compression v0.4.6 -> v0.4.12
Adding atomic-waker v1.1.2
Updating autocfg v1.1.0 -> v1.3.0
Updating backtrace v0.3.69 -> v0.3.73
Updating bitflags v2.5.0 -> v2.6.0
Updating bumpalo v3.15.4 -> v3.16.0
Updating bytes v1.5.0 -> v1.6.1
Updating camino v1.1.6 -> v1.1.7
Updating cargo-platform v0.1.7 -> v0.1.8
Updating cc v1.0.90 -> v1.1.6
Updating clru v0.6.1 -> v0.6.2
Updating crc32fast v1.4.0 -> v1.4.2
Updating crossbeam-channel v0.5.12 -> v0.5.13
Updating crossbeam-utils v0.8.19 -> v0.8.20
Updating either v1.10.0 -> v1.13.0
Updating encoding_rs v0.8.33 -> v0.8.34
Updating errno v0.3.8 -> v0.3.9 …
```
=> Add gix-curl feature

.github/workflows/rust-ci.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, src/index/git_remote.rs, tests/git.rs
```
Updating gix v0.63.0 -> v0.64.0
Updating gix-actor v0.31.4 -> v0.31.5
Updating gix-attributes v0.22.2 -> v0.22.3
Updating gix-command v0.3.7 -> v0.3.8
Updating gix-commitgraph v0.24.2 -> v0.24.3
Updating gix-config v0.37.0 -> v0.38.0
Updating gix-config-value v0.14.6 -> v0.14.7
Updating gix-credentials v0.24.2 -> v0.24.3
Updating gix-diff v0.44.0 -> v0.44.1
Updating gix-discover v0.32.0 -> v0.33.0
Updating gix-filter v0.11.2 -> v0.11.3
Updating gix-fs v0.11.1 -> v0.11.2
Updating gix-glob v0.16.3 -> v0.16.4
Updating gix-ignore v0.11.2 -> v0.11.3
Updating gix-index v0.33.0 -> v0.33.1
Updating gix-negotiate v0.13.1 -> v0.13.2
Updating gix-odb v0.61.0 -> v0.61.1
Updating gix-pack v0.51.0 -> v0.51.1
Updating gix-pathspec v0.7.5 -> v0.7.6
Updating gix-prompt v0.8.5 -> v0.8.6
Updating …
```
=> Update gix -> 0.64

CHANGELOG.md, src/utils.rs, tests/cache.rs
As noted in the comment, this changes the url kind from `u64` -> `usize` to match cargo, which unfortunately uses the default `derive(Hash)` which for enums uses `::core::intrinsics::discriminant_value` which for non-repr enums is...pointer size. This means the hash computed is different between 32 and 64-bit targets when they could easily be the same. :(
Resolves: https://github.com/EmbarkStudios/cargo-deny/issues/540#issuecomment-2262990465
=> Align with cargo

Cargo.lock, Cargo.toml, src/krate_name.rs, src/utils/flock/unix.rs, src/utils/git.rs, tests/flock.rs, tests/git.rs, tests/local.rs, tests/sparse.rs, tests/utils.rs
On top of https://github.com/EmbarkStudios/tame-index/pull/79
Update gix to v0.70
=> Update gix 0.70

CHANGELOG.md, src/utils.rs
Cargo 1.85.0 made more changes to how urls were hashed, notably, all urls are canonicalized unlike <1.85.0
This also removes support for git+ urls as that is not needed for this crate
=> Fix ident for non-crates.io urls

CHANGELOG.md, Cargo.lock, Cargo.toml
Upgrade to gix 0.71, which addresses [RUSTSEC-2025-0021](https://rustsec.org/advisories/RUSTSEC-2025-0021).
It would be nice to get a release out for use in the rustsec crate. (Happy to append a version bump commit, but not sure if this constitutes a semver-incompatible change.)
=> Upgrade gix to 0.71

src/index.rs
This PR makes a couple of changes to `index::IndexConfig`:
- its `API` field is now optional when deserializing from JSON, as specified by the Cargo reference;
- it now has an `auth_required` field, to reflect the `auth-required` JSON jey specific by the Cargo reference.
Note that the second bullet point is a breaking change, as the struct is fully public.
=> Complete IndexConfig according to current Cargo reference
